# version: '3'
services:
  airflow:
    labels:
      - "github.workflow=${GITHUB_WORKFLOW}"
      - "github.run_id=${GITHUB_RUN_ID}"
    image: apache/airflow:latest
    container_name: airflow
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__WEBSERVER__RBAC=True
      - AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX=True
      - AIRFLOW__WWW__USER_USERNAME=admin
      - AIRFLOW__WWW__USER_PASSWORD=admin
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./airflow_home:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
      - ./plugins:/opt/airflow/plugins
    networks:
      - airflow-network
    command: >
      bash -c "pip install -r /requirements.txt && airflow db init &&
               airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com &&
               airflow webserver"

  scheduler:
    labels:
      - "github.workflow=${GITHUB_WORKFLOW}"
      - "github.run_id=${GITHUB_RUN_ID}"
    image: apache/airflow:latest
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - ./airflow_home:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
      - ./plugins:/opt/airflow/plugins
    networks:
      - airflow-network
    command: >
      bash -c "pip install -r /requirements.txt && airflow scheduler"

networks:
  airflow-network:
    driver: bridge
