name: Run Capstone Pipeline
on:
  workflow_dispatch:  # Manual trigger
jobs:
  run-airflow-pipeline:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          path: ${{ github.sha }}
          
      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Start Airflow with Docker
        working-directory: ${{ github.sha }}
        run: |
          docker-compose up -d
          
      - name: Remove Old Files
        working-directory: ${{ github.sha }}
        run: |
          if [ -d "shapefiles" ]; then
            git rm -r --cached shapefiles/* || true
          fi
          
      - name: Trigger Airflow DAG
        working-directory: ${{ github.sha }}
        run: |
          docker exec airflow airflow dags trigger test_dag
          
      - name: Show IP address
        run: |
          ifconfig en0
          
      - name: Commit Changes
        working-directory: ${{ github.sha }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          if [ -d "shapefiles" ]; then
            git add -A shapefiles
            git diff --cached --quiet || git commit -m "Updated with new files"
            git push
          fi
          
      - name: Clean up stopped containers
        working-directory: ${{ github.sha }}
        run: |
          docker ps -q | xargs -r docker stop
          docker ps -aq | xargs -r docker rm
          docker container prune -f
          
      - name: Shut Down
        working-directory: ${{ github.sha }}
        run: |
          docker-compose down

      - name: Cleanup workspace
        if: always()
        run: |
          chmod -R 777 ${{ github.sha }} || true
          rm -rf ${{ github.sha }} || true
