name: Run Airflow Pipeline
on:
  workflow_dispatch:

jobs:
  run-airflow-pipeline:
    runs-on: self-hosted
    permissions:
      contents: write  # Needed for pushing changes
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Start Airflow
        run: |
          docker compose up -d
          # Wait for Airflow webserver to be ready
          sleep 5
          
      - name: Trigger DAG
        run: |
          docker exec airflow airflow dags trigger test_dag

      - name: Show IP address
        run: |
          ifconfig en0
          
      - name: Wait for DAG Completion
        run: |
          # Wait for DAG to complete
          sleep 5
          
      - name: Commit and Push Changes
        run: |
          if [ -d "shapefiles" ]; then
            git add shapefiles/
            git status
            if ! git diff --cached --quiet; then
              git commit -m "Update shapefiles from Airflow DAG run"
              git push
            fi
          fi
          
      - name: Cleanup
        if: always()  # Run this step even if previous steps fail
        run: |
          docker compose down --remove-orphans
          docker system prune -f
